[Issue 277] add cloud_init_disable_upgrade_packages option
hashicorp/packer-plugin-proxmox pull request #297
Opened 2024-10-30 13:31 UTC by mpywell

Add option to disable the `Upgrade Packages` setting on Cloud-Init Drives attached to VMs.

`Upgrade Packages` is introduced in Proxmox VE 8 and logic is added to only configure this option on backend versions that are compatible.

Closes #277

2026-04-07 02:13 UTC, CaptaiNiveau commented
Just started implementing this myself, until I stumbled upon this PR. @JenGoldstrich [you mentioned over here](https://github.com/hashicorp/packer-plugin-proxmox/pull/308#pullrequestreview-3064628944) that you wanted to discuss maintenance status of this plugin with the team - what's the current state of that? It'd be nice if small things like this PR were approved.

I need this option, because otherwise Arch Linux automatically upgrades its packages in the iso and immediately fills up its cowspace. Yes, I can increase the size of the cowspace afterwards, but just disabling auto upgrade is obviously the significantly better fix.

Thanks for all the nice IaC tooling, would love to see it improve :)

2026-04-07 03:11 UTC, CaptaiNiveau commented
Oh btw, I rebased that PR and fixed the small merge conflicts [over here](https://github.com/CaptaiNiveau/packer-plugin-proxmox/tree/feat/277_cloud_init_upgrade_packages). I'll be testing it out in the next few days but I doubt that there will be any issues.

2026-04-07 03:35 UTC, CaptaiNiveau commented
Hm, sadly it doesn't seem to work as expected yet. Just installed the plugin, but swapping it on/off doesn't change anything about the `upgrade packages` flag in Proxmox Cloud Init. Hm, I'll try to debug this.

2026-04-07 03:47 UTC, CaptaiNiveau commented
Ah, that PR actually only focused on the resulting template. I expanded on it and also use this variable if the vm is cloned instead of the iso. That behavior is in line with other existing variables, like the ssh public key. That one is also pulled in from the common communicator module into the Cloud Init configuration of the cloned vm.

2026-04-07 08:58 UTC, mpywell commented
Hey @CaptaiNiveau good catch, I must have missed adding this for the clone builder back when I submitted this PR 2 years ago. I do hope this repo gets some attention, I lost momentum as each PR I wrote had a long wait before being reviewed, some like this one are still awaiting an initial review.

2026-07-03 11:42 UTC, tanmay-hc commented on builder/proxmox/common/step_finalize_config.go
> +	Version() (proxmox.Version, error)
This introduces a new `version` dependency on every finalize path, even when `cloud_init` is off. That changes existing behavior and can now fail builds unrelated to this option. Can we move the version lookup into the exact branch where we actually need to decide whether to write `ciupgrade`?

2026-07-03 11:43 UTC, tanmay-hc commented on builder/proxmox/common/step_finalize_config.go
> +					}
This also changes the default behavior: when the new field is omitted, we still write `ciupgrade=true`. That means existing templates/clones with `ciupgrade=false` can get flipped on upgrade. We probably need tri-state semantics here, or to only send `ciupgrade` when the user explicitly set the option.

2026-07-03 11:44 UTC, tanmay-hc requested changes
I know the review is a bit too late. Apologies for that.
Please address the comments and do a rebase.
We should be good to merge.

2026-07-03 16:24 UTC, mpywell commented
Hi @tanmay-hc, have rebased and made some adjustments.

- CloudInitDisableUpgradePackages is now Trilean
- Version is only called if the Trilean has a set value
- I've added the functionality to the clone builder to resolve @CaptaiNiveau's earlier comments

2026-07-06 05:37 UTC, tanmay-hc approved these changes

2026-07-06 05:37 UTC, merged